apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: monitoring
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: zabbix
  MYSQL_USER: zabbix
  MYSQL_PASSWORD: zabbixpassword
